#################################################################
## Automations
#################################################################

- alias: Dining Room On
  trigger:
    - platform: mqtt
      topic: 'dining_room/switch/light'
      payload: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: light.dining_room

- alias: Dining Room Off
  trigger:
    - platform: mqtt
      topic: 'dining_room/switch/light'
      payload: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: light.dining_room

#Tasker publishes to MQTT when alarm clock goes off
- alias: Morning Alarm - Bedroom On
  trigger:
    - platform: mqtt
      topic: 'bedroom/switch/light'
      payload: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: light.sean_bedroom

- alias: Sean TV On
  trigger:
    - platform: mqtt
      topic: 'bedroom/switch/tv'
      payload: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.broadlink_switch

- alias: Sean TV Off
  trigger:
    - platform: mqtt
      topic: 'bedroom/switch/tv'
      payload: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.broadlink_switch

- alias: Turn on light when arriving home
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: device_tracker.phone_phone
      from: 'not_home'
      to: 'home'
  condition:
    - condition: time
      after: '17:30:00'
  action:
    - service: light.turn_on
      entity_id: light.sean_bedroom
