homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 20
  unit_system: metric
  time_zone: America/Vancouver

frontend:

http:
  api_password: !secret api_password 
  base_url: !secret base_url

updater:

discovery:

conversation:

history:

logbook:

sensor:
  - platform: yweather
    monitored_conditions:
      - weather_current
      - temp_min
      - temp_max
      - temperature

tts:
  platform: google

insteon_local:
  host: !secret insteon_host
  username: !secret insteon_user
  password: !secret insteon_pass

light:
  - platform: insteon_local
  
switch:
  - platform: insteon_local

device_tracker:
  - platform: owntracks
  
mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pass
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true
 
automation: !include automation.yaml
group: !include groups.yaml