homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 20
  unit_system: metric
  time_zone: America/Vancouver
  customize: !include customize.yaml

frontend:

http:
  api_password: !secret api_password 
  base_url: !secret base_url

updater:

discovery:

conversation:

history:

logbook:

sensor:
  - platform: yweather
    monitored_conditions:
      - weather_current
      - temp_min
      - temp_max
      - temperature

tts:
  platform: google

insteon_local:
  host: !secret insteon_host
  username: !secret insteon_user
  password: !secret insteon_pass

light:
  - platform: insteon_local
  
switch:
  - platform: insteon_local
  - platform: broadlink
    host: !secret broadlink_ip_address
    mac: !secret broadlink_mac_address
    switches:
      sean_tv:
        command_on: 'JgBUAFATExQnEyYUJxMUEyYUFBMnExQTExQTExQAAx5NFBIVJhQmFCcTFBMnExMUJxMTFBMTExQUAAMeTRQSFCcTJxQnExMUJhQSFSYUExMTFBQTFAANBQAAAAA='
        command_off: 'JgCMAFATKBMVEikSFRMoExQTFRIpEhUTFRIVEhUAA01QEikSFRMoExUSKRIVExUSKRIVEhUTFRIVAANMUBMoExUSKRIVEygTFRIVEikSFRMVEhUTFAADTVASKRIVEygTFRIpEhUSFRMoExUSFRIVExUAA0xQEygTFRIpEhUSKRIVExUSKRIVEhUTFRIVAA0FAAAAAAAAAAAAAAAA='
      sean_tv_play:
        command_on: 'JgCqAFATFRIpEhUTKBMoExUSFRMoEygTKBMVEikSFRMUEygAAohQExQTKBMVEikSKRIVExUSKRIpEikSFRMoExQTFRIpAAKHUBMVEikSFRMoEygTFBMVEikSKRIpEhUTKBMVEhUTKAACf1ASFRIpEhUTKBMoExUSFRMoEygTKBMVEikSFRMUEygAAn9QEhUTKBMVEikSKRIVExQTKBMoEykSFRIpEhUTFRIpAA0FAAAAAAAAAAAAAAAAAAA='
        command_off: 'JgCqAFASKRIVExQTKBMpEhUSFRMoEygTKBMVEikSFRMUEygAAohQEikSFRMVEikSKRIVExQTKBMoEykSFRIpEhUTFRIpAAKHUBMoExUSFRIpEikSFRMVEikSKRIpEhUTKBMVEhUSKQACh1ATKBMVEhUTKBMoExUSFRMoEygTKBMVEikSFRMUEygAAohQEygTFBMVEikSKRIVExUSKRIpEikSFRMoExUSFRIpAA0FAAAAAAAAAAAAAAAAAAA='

device_tracker:
  - platform: owntracks
  
mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pass
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true
    
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
 
automation: !include automation.yaml
group: !include groups.yaml